-- STC Assignment Form (solar + battery variants), matching the structure of
-- real assignment forms generated by industry STC-processing platforms:
-- owner/property/STC details, per-unit equipment tables with serial numbers,
-- designer/installer/electrician details, customer declaration + signature,
-- and installer/designer/retailer written statements.

alter table companies add column stc_agent_name text;
alter table companies add column stc_agent_abn text;
alter table companies add column stc_agent_address text;

alter table installers add column company_name text;
alter table installers add column phone text;
alter table installers add column email text;
alter table installers add column address_line text;
alter table installers add column accreditation_type text;

alter table jobs add column customer_abn text;
alter table jobs add column designer_installer_id uuid references installers (id) on delete set null;
alter table jobs add column electrician_installer_id uuid references installers (id) on delete set null;
alter table jobs add column battery_installation_type text default 'New';
alter table jobs add column battery_connection_type text;
alter table jobs add column changed_default_manufacturer_setting boolean;
alter table jobs add column part_of_aggregated_control boolean;
alter table jobs add column previously_received_stc_discount boolean;
alter table jobs add column vpp_capable boolean;
alter table jobs add column retailer_involved_in_procurement boolean;
alter table jobs add column stc_assignment_signed_by_name text;
alter table jobs add column stc_assignment_signature text;
alter table jobs add column stc_assignment_signed_at timestamptz;

alter table job_equipment add column serial_numbers text[] not null default '{}';
